sudo: required 
language: generic
node_js:
    - "stable"
    
services: 
    - docker

deploy:
  - provider: elasticbeanstalk
    region: us-east-1
    app: "sample-docker-react"
    env: "Sampledockerreact-env"

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY

    bucket_name: "elasticbeanstalk-us-east-1-092354816535"

    bucket_path: "EBApptest"

    on:
      branch: main
  