sudo: required 
language: node_js
node_js:
    - "stable"

services: 
    - docker
before_install: 
    ###- docker build -t yuwangjr/sample-app -f Dockerfile.dev .
    - docker build -t sample-app .
script:     
    ### - docker run -e CI=true yuwangjr/sample-app npm run test -- --coverage --watchAll=false.
    ### - docker run -p 80:80 yuwangjr/sample-app
    - docker run -d -p 80:80 sample-app 

after_deploy:
  - echo "done deploying"

deploy:
  provider: elasticbeanstalk
  access_key_id: "$ACCESSKEYID"
  secret_access_key: "$SECRETACCESSKEY1"
  region: "us-east-1"  
  app: "sample-docker-react"
  env: "Sampledockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-092354816535"
  bucket_path: "EBApptest" 
  on:
    branch: main